// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8NtVPkNfe-iQqFvUQx1giUESO0LmLX-0',
    appId: '1:159639375418:web:fd9d4e33f112c43ef72f03',
    messagingSenderId: '159639375418',
    projectId: 'flutter-sentiment-analys-fe044',
    authDomain: 'flutter-sentiment-analys-fe044.firebaseapp.com',
    storageBucket: 'flutter-sentiment-analys-fe044.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPuqy3FOzy6ly1KVSQ35Wn_7_HdQO_788',
    appId: '1:159639375418:android:727d26ce43ec5d54f72f03',
    messagingSenderId: '159639375418',
    projectId: 'flutter-sentiment-analys-fe044',
    storageBucket: 'flutter-sentiment-analys-fe044.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdXELsmhY10mTW6SrKe9STEp5p-YR2Pj4',
    appId: '1:159639375418:ios:150626a36637b02bf72f03',
    messagingSenderId: '159639375418',
    projectId: 'flutter-sentiment-analys-fe044',
    storageBucket: 'flutter-sentiment-analys-fe044.firebasestorage.app',
    iosBundleId: 'com.example.sentimentAnalysis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdXELsmhY10mTW6SrKe9STEp5p-YR2Pj4',
    appId: '1:159639375418:ios:150626a36637b02bf72f03',
    messagingSenderId: '159639375418',
    projectId: 'flutter-sentiment-analys-fe044',
    storageBucket: 'flutter-sentiment-analys-fe044.firebasestorage.app',
    iosBundleId: 'com.example.sentimentAnalysis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8NtVPkNfe-iQqFvUQx1giUESO0LmLX-0',
    appId: '1:159639375418:web:f0830f701d14a746f72f03',
    messagingSenderId: '159639375418',
    projectId: 'flutter-sentiment-analys-fe044',
    authDomain: 'flutter-sentiment-analys-fe044.firebaseapp.com',
    storageBucket: 'flutter-sentiment-analys-fe044.firebasestorage.app',
  );

}